---
title: "2020 data merging"
author: "Fenton Sun"
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
edu_2020 <- read.csv("2020_Education rate_Cleaned.csv")
rb_2020 <- read.csv("2020_rent burden_cleaned.csv")
pov_2020 <-read.csv("Cleaned Pov 2020.csv")
crowd_2020 <- read.csv("crowd_20.csv")

```

## 1. Merging the dataset

```{r merging}
edu <- separate(data = edu_2020, col = GEO_ID, sep = c(9), into = c("GEO_ID", "GEOID"))
rb  <- separate(data = rb_2020,  col = GEO_ID, sep = c(9), into = c("GEO_ID", "GEOID"))
pov <- separate(data = pov_2020, col = GEO_ID, sep = c(9), into = c("GEO_ID", "GEOID"))
names(crowd_2020)[2] <- "GEOID"
merge1 = merge(edu, rb, by = "GEOID")
factors_2020 = merge(merge1, pov, by = "GEOID")
factors_2020_final <- factors_2020 %>%
  dplyr::select(GEOID, NAME.x, Education.rate, percentage, Percent.Population.Below.Poverty.Line)
names(factors_2020_final)[4] <- "Rent_burden"
write.csv(factors_2020_final,"C:\\Users\\sunzhixing\\Desktop\\ factors2020.csv")
```


