---
title: "cleaning2019"
author: "Kevin Ding"
date: "3/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = setdiff(ls(), lsf.str()))
install.packages("tidyverse")
library(tidyverse)
```


## import Y datasets
```{r}
ys=read.csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/newdata/y variable/ymix.csv")
y2019=ys%>%filter(Year==2019)
y2019=y2019%>%mutate(avgYearlyEvictionRate=AvgMonthlyEvictionRate*12)
```

## import X datasets
```{r}
xinit=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/productDownload_2022-03-22T163533/2019 data.csv")
xinit=xinit[-c(1),]

## import poverty rate data from Matt
pov=read.csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/Cleaned_Pov_19.csv")
pov=rename(pov,TractID=GEOID,povertyRate="X..Population.below.poverty.2019")
pov=pov%>%select(TractID,povertyRate)

## import educ data from hyesun
educ=read.csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/2019_Education rate_Cleaned.csv")
educ=educ%>%mutate(TractID=substr(GEO_ID,10,20))

## import rent burden
rent=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/2019_Rent burden_Cleaned.csv")
rent=rename(rent,TractID=GEOID)

## import insurance data
uninsur=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/Uninsurance_19_20_UNcleaned/ACSST5Y2019.S2701_data_with_overlays_2022-03-25T132633.csv")
uninsur=uninsur%>%select(GEO_ID,S2701_C05_001E)
uninsur=uninsur[-c(1),]
uninsur=uninsur%>%mutate(TractID=substr(GEO_ID,10,20))
uninsur=rename(uninsur,uninsurRate=S2701_C05_001E)

## import race data
mino=read.csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/Race_18_19.csv")
mino=rename(mino,TractID=FIPS)
mino=rename(mino,minority=X2019)

merged=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/data2019.csv")
```

## extract variables
```{r}
xs=xinit%>%select(GEO_ID,unemp=S2301_C04_001E)
xs=xs%>%mutate(TractID=substr(GEO_ID,10,20))
xs=merge(xs,pov,by.x = "TractID",by.y = "TractID")
xs=merge(xs,educ,by.x = "TractID",by.y = "TractID")
xs=merge(xs,rent,by.x = "TractID",by.y = "TractID")
xs=merge(xs,uninsur,by.x = "TractID",by.y="TractID")
xs=xs[-c(2),]

```


## merge datasets
```{r}
data2019=merge(xs,y2019,by.x = "TractID",by.y = "TractID")

data2019=merge(merged,mino,by.x = "TractID",by.y = "TractID")

```


## adding renter unit percentage variable 
```{r}
rent=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/renter-occupied/Renter-occupied housing units_2019,2020/ACSDT5Y2019.B25003_data_with_overlays_2022-03-28T213336.csv")
rent=rent%>%mutate(TractID=substr(GEO_ID,10,20))
rent=rent[-c(1),]
rent=rent%>%mutate(renterRate=as.numeric(B25003_003E)/as.numeric(B25003_001E))


data=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/data2019.csv")
data2019=merge(data,rent,by.x = "TractID",by.y = "TractID")
```

## rename and dropping unnecessary columns
```{r}
data=read_csv("/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/data2019.csv")
data=data[,-c(4,5,10,11,13,14,16,18,19,22,23,27,28,30)]
data=rename(data,unemp_rate=unemp,poverty_rate=povertyRate,education_rate="Education.rate",uninsur_rate=uninsurRate,minority_rate=minority,avg_yearly_evic_rate=avgYearlyEvictionRate)
data=rename(data,rent_burden="X..Gross.rent.30.0.percent.of.income.or.greater.2019")

```


## export datasets
```{r}
write_csv(data,"/Users/KevinDing/Desktop/spring-2022/qtm-capstone/latest data/data2019.csv")

```


