---
title: "Data Cleaning"
author: "ARC Capstone Team"
date: "4/5/2022"
output: html_document
---

## Import and Load Package
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, prompt=FALSE, message = FALSE,comment=NA )
options(repos = list(CRAN="http://cran.rstudio.com/"))
rm(list = setdiff(ls(), lsf.str()))
install.packages("tidyverse")
library(tidyverse)
library(dplyr)
```

## Import Raw Data

### Import Explanatory Variable Data
```{r}
# Import poverty dataset of year 2020 from the U.S. Census Bureau website
pov2020 <- read.csv("../datasets/poverty_2020.csv")
# Import poverty dataset of year 2018 and 2019 from the Neighborhood Nexus website
pov1819 <- read.csv("../datasets/poverty_18_19.csv")


# Import 2019 and 2020 rent burden data 
rent_burden_19 <- read.csv("../datasets/rent_burden_2019.csv")
rent_burden_20 <- read.csv("../datasets/rent_burden_2020.csv")


# Import uninsurance rate datasets of years 2019 and 2020 from the U.S. Census Bureau website
uninsurance19<-read.csv("../datasets/uninsured_2019.csv")
uninsurance20<-read.csv("../datasets/uninsured_2020.csv")


# Import race dataset of year 2020 from the U.S. Census Bureau website
race2020 <- read.csv("../datasets/race_2020.csv")
# Import race dataset of year 2018 and 2019 from the Neighborhood Nexus website
race1819 <- read.csv("../datasets/race_18_19.csv")

#Import unemployment rate datasets of years 2019 and 2020 from the U.S. Census Bureau website
unemp19<-read.csv("../datasets/unemp_2019.csv")
unemp20<-read.csv("../datasets/unemp_2020.csv")


# Import education data that estimates education attainment
edu_20 <-read.csv("../datasets/education_2020.csv")
edu_19 <- read.csv("../datasets/education_2019.csv")


## Import renter occupied housing unit data from the U.S. Census Bureau website for 2019
rent19=read.csv("../datasets/renter_occupied_2019.csv")
rent20=read.csv("../datasets/renter_occupied_2020.csv")

```

### Import Dependent Variable Data
```{r}
eviction=read_csv("../datasets/evictions.csv")
household=read_csv("../datasets/household_count.csv")
```

## Clean Raw Data

### Extract and Clean Explanatory Variable Data
```{r}
## clean poverty data for 2019 and 2020

# Select GEO_ID, NAME, percent in poverty columns for 2020 data
pov_2020 <- pov2020[-1,] %>%
  rename("TractID" = "GEO_ID", "PovertyPercent" = "S1701_C03_001E") %>%
  mutate("PovertyRate" = as.numeric(as.character(PovertyPercent))/100) %>% mutate(TractID = substr(TractID, 10, 20)) %>%
  select("TractID", "PovertyRate") 

# 2019 data
pov19 <- pov1819[,c(1,3,6)]
names(pov19) <- c("TractID", "COUNTY", "PovertyPercent")
# Filter 5 counties and rename columns
pov19 <- pov19 %>%
  filter(COUNTY %in% c("Fulton", "DeKalb", "Gwinnett", "Clayton", "Cobb")) %>% 
  mutate("PovertyRate" = as.numeric(as.character(PovertyPercent))/100) %>% select(TractID, COUNTY, PovertyRate)



## clean education data for 2019 and 2020
### Education - Rate of people who got bach degree or higher
### 2019 and 2020

# Define a function which cleans the educaton data
education_cleaning <- function(df)  { 
edu <- df %>%
  select(GEO_ID, NAME, S2301_C01_035E, S2301_C01_021E)
# Drop the first row which contains description of the data
# and save it as a new dataframe
edu_new <- edu[-1,]
# Create a column that contains # of people who got bach degree
edu_new$bach<-as.numeric(edu_new$S2301_C01_035E)
# Create a column that contains population living in different census tracts
edu_new$pop<-as.numeric(edu_new$S2301_C01_021E)
# Create a column that contains percentage of ppl who got bach degrees or higher
edu_new$education_rate_bachelors_or_higher <- edu_new$bach/edu_new$pop
# Create a dataframe that only contains columns that are relevant to our analyses
edu_new1 <- edu_new %>% mutate(GEO_ID = substr(GEO_ID, 10, 20)) %>%
  select(GEO_ID, education_rate_bachelors_or_higher) 
# Rename columns
colnames(edu_new1) <- c('TractID', 'EducationRate')
return(edu_new1)
}
education_rate_20 <- education_cleaning(edu_20)
education_rate_19 <- education_cleaning(edu_19)




### Uninsured rate
### 2019 & 2020

# Define a function that drops, renames column
uninsur_cleaning <- function(uninsur){
  uninsur=uninsur[-c(1),]
  uninsur=uninsur %>% select(GEO_ID, NAME, S2701_C05_001E)
  uninsur=uninsur%>%mutate(TractID=substr(GEO_ID,10,20), UninsurRate = as.numeric(as.character(S2701_C05_001E))/100)
  uninsur=uninsur%>%select(TractID,UninsurRate)
  return(uninsur)
}

uninsurance_19=uninsur_cleaning(uninsurance19)
uninsurance_20=uninsur_cleaning(uninsurance20)



### Minority: Percentage of non-white population
### 2020

# Select GEO_ID, NAME, total population, and the white alone population columns for 2019 data
# Calculate Minority percentage
race_2020 <- race2020[-c(1),] %>%
  select("GEO_ID", "NAME", "P1_001N", "P1_003N") %>%
  mutate(MinorityRate = (as.numeric(as.character(P1_001N)) - as.numeric(as.character(P1_003N)))/ as.numeric(as.character(P1_001N))) %>% mutate(TractID=substr(GEO_ID,10,20)) %>% select(TractID, MinorityRate)

# 2019
race19 <- race1819[,c(1,3,6)]
names(race19) <- c("TractID", "COUNTY", "MinorityPercent")
race_19 <- race19 %>%
  filter(COUNTY %in% c("Fulton", "DeKalb", "Gwinnett", "Clayton", "Cobb")) %>% 
  mutate("MinorityRate" = as.numeric(as.character(MinorityPercent))/100) %>%
  select("TractID", "COUNTY", "MinorityRate")



### Renter Occupied
### 2019 

## Remove the first row which contains the header
rent19=rent19[-c(1),]
## Calculate the renter occupied housing rate and rename it as renter_rate for 2019 data
rent19=rent19%>%mutate(RenterRate=as.numeric(B25003_003E)/as.numeric(B25003_001E))
rent19=rent19%>%select(GEO_ID,RenterRate)
rent19=rent19%>%mutate(TractID=substr(GEO_ID,10,20))
rent19=rent19%>%select(TractID,RenterRate)

# 2020
## Import renter occupied housing unit data from the U.S. Census Bureau website for 2020
rent20=rent20[-c(1),]

## Calculate the renter occupied housing rate and rename it as renter_rate for 2020 data
rent20=rent20%>%mutate(RenterRate=as.numeric(B25003_003E)/as.numeric(B25003_001E))
rent20=rent20%>%select(GEO_ID,RenterRate)
rent20=rent20%>%mutate(TractID=substr(GEO_ID,10,20))
rent20=rent20%>%select(TractID,RenterRate)


### Unemployment Rate
### 2019 & 2020

# Define a function that cleans unemployment csv files
unemp_cleaning <- function(unemp){
  unemp <- unemp%>%select(GEO_ID, NAME, S2301_C04_001E)
  unemp <- unemp[-1, ] %>% mutate("TractID"=substr(GEO_ID,10,20), 
                                  "UnempRate"=as.numeric(as.character(S2301_C04_001E))/100)
  unemp <- unemp %>% select(TractID, UnempRate)
  return(unemp)
}
unemp19=unemp_cleaning(unemp19)
unemp20=unemp_cleaning(unemp20)





### Rent Burden
### 2019

# Rename variable
names(rent_burden_19)[6] <- "RentBurdenPerc"
# Filter 5 county area
rent_burden_19 <- rent_burden_19 %>%
  filter(COUNTY == "Fulton" | COUNTY == "DeKalb"| COUNTY == "Cobb" | COUNTY == "Clayton" | COUNTY == "Gwinnett") %>% mutate(RentBurdenRate = RentBurdenPerc/100)
  
# rename columns
rent_burden_19 <- rename(rent_burden_19,TractID=GEOID)
# Drop columns that are irrelevant to analyses
rent_burden_19 <- rent_burden_19 %>% select(TractID, COUNTY, RentBurdenRate)


# 2020
# Select GEO_ID, NAME, and columns that shows rent payment consist 30 percent or more of household income
new_20 <- rent_burden_20 %>%
  select(B25070_001E, B25070_007E, B25070_008E, B25070_009E, B25070_010E, GEO_ID, NAME)

# Rename columns
new_20_1 <- new_20[-1,]
new_20_1$total<-as.numeric(new_20_1$B25070_001E)
new_20_1$rent_30<-as.numeric(new_20_1$B25070_007E)
new_20_1$rent_35<-as.numeric(new_20_1$B25070_008E)
new_20_1$rent_40<-as.numeric(new_20_1$B25070_009E)
new_20_1$rent_50<-as.numeric(new_20_1$B25070_010E)

# Calculate the rent burden percentage
new_20_1$sum <- new_20_1$rent_30+new_20_1$rent_35+new_20_1$rent_40+new_20_1$rent_50
new_20_1$percentage <- new_20_1$sum/new_20_1$total

rent_burden_20 <- new_20_1 %>% mutate(TractID = substr(GEO_ID, 10, 20))  %>%
  select(TractID, percentage) 
rent_burden_20 <- rename(rent_burden_20,RentBurdenRate=percentage)


 


```


### Extract and Clean Dependent Variable Data
```{r}
# import household count data from neighborhood nexus
household <- read.csv("../datasets/household_count.csv", skip = 1)
# import eviction filing data
eviction  <- read.csv("../datasets/evictions.csv")

compute_evic_rate <- function(eviction_df, household_df, annual = TRUE){
  # Split filing date into days, month, and years
  eviction_df <- separate(data = eviction, col = FilingDate, sep = "/", 
                 into = c("Dates","Month","Year"))
  if (annual){# Compute annual total eviction filings
      df <- eviction_df%>% group_by(TractID, Year) %>% 
  summarize("TotalFilings" = sum(TotalFilings), )
    
  }
    else {# If annual == FALSE, compute monthly total eviction filings
      df <- df %>% group_by(TractID, CountyID, Year, Month) %>% 
  summarize("TotalFilings" = sum(TotalFilings),)}
  
  # Remove observations that are missing census tract ID
  df <- df[df$TractID != 99999999999, ]
  # Rename variable of household data 
  names(household_df)[6] <- "TotalHousehold2019"
  # Subset household_df
  df2 <- household_df[, c("GEOID", "TotalHousehold2019")]
  # Merge eviction filing data with household count data
  df3 <- inner_join(df, df2, by=c("TractID" = "GEOID"))
  # Compute eviction rate
  df3 <- df3 %>% mutate("EvictionRate" = TotalFilings/TotalHousehold2019)
  # Remove observations with NAs
  df3 <- na.omit(df3)
  return(df3)
}

evic=compute_evic_rate(eviction,household)
```




## Merge Data

### Merge and Export 2019 Data
```{r}
y2019=evic%>%filter(Year==19)
data19=merge(y2019,pov19)
data19=merge(data19,education_rate_19)
data19=merge(data19,uninsurance_19)
data19=merge(data19,race_19)
data19=merge(data19,rent19)
data19=merge(data19,unemp19)
data19=merge(data19,rent_burden_19)

### test how many unique tract regions we have
test=data19$TractID
length(unique(test))

write.csv(data19,"../datasets/data2019.csv")

```


### Merge and Export 2020 Data
```{r}
y2020=evic%>%filter(Year==20)
data20=merge(y2020,pov_2020)
data20=merge(data20,education_rate_20)
data20=merge(data20,uninsurance_20)
data20=merge(data20,race_2020)
data20=merge(data20,rent20)
data20=merge(data20,unemp20)
data20=merge(data20,rent_burden_20)

### test how many unique tract regions we have
test=data20$TractID
length(unique(test))


write.csv(data20,"../datasets/data2020.csv")
```

